In [2]:
import numpy as np
import pandas as pd

In [8]:
df= pd.read_csv("/content/train.csv")

In [9]:
df1= pd.read_csv("/content/test.csv")

In [10]:
df2=pd.read_csv("/content/gender_submission.csv")

In [13]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [11]:
df1.head(2)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S

In [12]:
df2.head(2)

   PassengerId  Survived
0          892         0
1          893         1

In [14]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
for i in df:
  df[i]=df[i].fillna(df[i].mode()[0])

In [16]:
for i in df:
  if df[i].dtypes == 'O':
    print(i)

Name
Sex
Ticket
Cabin
Embarked

In [17]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [18]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df1.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [19]:
df1['Age'].fillna(df1['Age'].mean(), inplace=True)

In [20]:
df1['Age']=pd.to_numeric(df1['Age'])

In [21]:
df1.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [22]:
df1["Cabin"].unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object)

In [23]:
for i in df1:
  df1[i]=df1[i].fillna(df1[i].mode()[0])

In [24]:
for i in df1:
  if df1[i].dtypes == 'O':
    print(i)

Name
Sex
Ticket
Cabin
Embarked

In [25]:
df1.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [26]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [27]:
df2.isnull().sum()

PassengerId    0
Survived       0
dtype: int64

In [28]:
for i in df.columns:
  print(i,df[i].sort_values().unique(),"\n",sep="\n")

PassengerId
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612
 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630
 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648
 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666
 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684
 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702
 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720
 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738
 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756
 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774
 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792
 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809 810
 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827 828
 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845 846
 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863 864
 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881 882
 883 884 885 886 887 888 889 890 891]


Survived
[0 1]


Pclass
[1 2 3]


Name
['Abbing, Mr. Anthony' 'Abbott, Mr. Rossmore Edward'
 'Abbott, Mrs. Stanton (Rosa Hunt)' 'Abelson, Mr. Samuel'
 'Abelson, Mrs. Samuel (Hannah Wizosky)' 'Adahl, Mr. Mauritz Nils Martin'
 'Adams, Mr. John' 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)'
 'Aks, Mrs. Sam (Leah Rosen)' 'Albimona, Mr. Nassef Cassem'
 'Alexander, Mr. William' 'Alhomaki, Mr. Ilmari Rudolf' 'Ali, Mr. Ahmed'
 'Ali, Mr. William' 'Allen, Miss. Elisabeth Walton'
 'Allen, Mr. William Henry' 'Allison, Master. Hudson Trevor'
 'Allison, Miss. Helen Loraine'
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)'
 'Allum, Mr. Owen George'
 'Andersen-Jensen, Miss. Carla Christine Nielsine' 'Anderson, Mr. Harry'
 'Andersson, Master. Sigvard Harald Elias'
 'Andersson, Miss. Ebba Iris Alfrida' 'Andersson, Miss. Ellis Anna Maria'
 'Andersson, Miss. Erna Alexandra' 'Andersson, Miss. Ingeborg Constanzia'
 'Andersson, Miss. Sigrid Elisabeth' 'Andersson, Mr. Anders Johan'
 'Andersson, Mr. August Edvard ("Wennerstrom")'
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)'
 'Andreasson, Mr. Paul Edvin' 'Andrew, Mr. Edgardo Samuel'
 'Andrews, Miss. Kornelia Theodosia' 'Andrews, Mr. Thomas Jr'
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)'
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)'
 'Arnold-Franchi, Mr. Josef'
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)' 'Artagaveytia, Mr. Ramon'
 'Asim, Mr. Adola' 'Asplund, Master. Clarence Gustaf Hugo'
 'Asplund, Master. Edvin Rojj Felix' 'Asplund, Miss. Lillian Gertrud'
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'
 'Astor, Mrs. John Jacob (Madeleine Talmadge Force)'
 'Attalah, Miss. Malake' 'Attalah, Mr. Sleiman'
 'Aubart, Mme. Leontine Pauline' 'Augustsson, Mr. Albert'
 'Ayoub, Miss. Banoura' 'Backstrom, Mr. Karl Alfred'
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)'
 'Baclini, Miss. Eugenie' 'Baclini, Miss. Helene Barbara'
 'Baclini, Miss. Marie Catherine' 'Baclini, Mrs. Solomon (Latifa Qurban)'
 'Badt, Mr. Mohamed' 'Bailey, Mr. Percy Andrew' 'Balkic, Mr. Cerin'
 'Ball, Mrs. (Ada E Hall)' 'Banfield, Mr. Frederick James'
 'Barah, Mr. Hanna Assi' 'Barbara, Miss. Saiide'
 'Barbara, Mrs. (Catherine David)' 'Barber, Miss. Ellen "Nellie"'
 'Barkworth, Mr. Algernon Henry Wilson' 'Barton, Mr. David John'
 'Bateman, Rev. Robert James' 'Baumann, Mr. John D'
 'Baxter, Mr. Quigg Edmond'
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)' 'Bazzani, Miss. Albina'
 'Beane, Mr. Edward' 'Beane, Mrs. Edward (Ethel Clarke)'
 'Beavan, Mr. William Thomas' 'Becker, Master. Richard F'
 'Becker, Miss. Marion Louise' 'Beckwith, Mr. Richard Leonard'
 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)'
 'Beesley, Mr. Lawrence' 'Behr, Mr. Karl Howell'
 'Bengtsson, Mr. John Viktor' 'Berglund, Mr. Karl Ivar Sven'
 'Berriman, Mr. William John' 'Betros, Mr. Tannous'
 'Bidois, Miss. Rosalie' 'Bing, Mr. Lee'
 'Birkeland, Mr. Hans Martin Monsen' 'Bishop, Mr. Dickinson H'
 'Bishop, Mrs. Dickinson H (Helen Walton)' 'Bissette, Miss. Amelia'
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan'
 'Blackwell, Mr. Stephen Weart' 'Blank, Mr. Henry'
 'Bonnell, Miss. Elizabeth' 'Bostandyeff, Mr. Guentcho'
 'Boulos, Miss. Nourelain' 'Boulos, Mr. Hanna'
 'Boulos, Mrs. Joseph (Sultana)' 'Bourke, Miss. Mary' 'Bourke, Mr. John'
 'Bourke, Mrs. John (Catherine)' 'Bowen, Mr. David John "Dai"'
 'Bowerman, Miss. Elsie Edith' 'Bracken, Mr. James H'
 'Bradley, Mr. George ("George Arthur Brayton")'
 'Braund, Mr. Lewis Richard' 'Braund, Mr. Owen Harris'
 'Brewe, Dr. Arthur Jackson' 'Brocklebank, Mr. William Alfred'
 'Brown, Miss. Amelia "Mildred"' 'Brown, Mr. Thomas William Solomon'
 'Brown, Mrs. James Joseph (Margaret Tobin)'
 'Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)'
 'Bryhl, Mr. Kurt Arnold Gottfrid' 'Burke, Mr. Jeremiah'
 'Burns, Miss. Elizabeth Margaret' 'Buss, Miss. Kate'
 'Butler, Mr. Reginald Fenton' 'Butt, Major. Archibald Willingham'
 'Byles, Rev. Thomas Roussel Davids' 'Bystrom, Mrs. (Karolina)'
 'Cacic, Miss. Marija' 'Cacic, Mr. Luka' 'Cairns, Mr. Alexander'
 'Calderhead, Mr. Edward Pennington' 'Caldwell, Master. Alden Gates'
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)' 'Calic, Mr. Jovo'
 'Calic, Mr. Petar' 'Cameron, Miss. Clear Annie' 'Campbell, Mr. William'
 'Canavan, Miss. Mary' 'Cann, Mr. Ernest Charles'
 'Caram, Mrs. Joseph (Maria Elias)' 'Carbines, Mr. William'
 'Cardeza, Mr. Thomas Drake Martinez' 'Carlsson, Mr. August Sigfrid'
 'Carlsson, Mr. Frans Olof' 'Carr, Miss. Helen "Ellen"'
 'Carrau, Mr. Francisco M' 'Carter, Master. William Thornton II'
 'Carter, Miss. Lucile Polk' 'Carter, Mr. William Ernest'
 'Carter, Mrs. Ernest Courtenay (Lilian Hughes)'
 'Carter, Mrs. William Ernest (Lucile Polk)'
 'Carter, Rev. Ernest Courtenay' 'Cavendish, Mr. Tyrell William'
 'Celotti, Mr. Francesco' 'Chaffee, Mr. Herbert Fuller'
 'Chambers, Mr. Norman Campbell'
 'Chambers, Mrs. Norman Campbell (Bertha Griggs)'
 'Chapman, Mr. Charles Henry' 'Chapman, Mr. John Henry'
 'Charters, Mr. David' 'Cherry, Miss. Gladys'
 'Chibnall, Mrs. (Edith Martha Bowerman)' 'Chip, Mr. Chang'
 'Christmann, Mr. Emil' 'Christy, Miss. Julie Rachel'
 'Chronopoulos, Mr. Apostolos'
 'Clarke, Mrs. Charles V (Ada Maria Winfield)' 'Cleaver, Miss. Alice'
 'Clifford, Mr. George Quincy' 'Coelho, Mr. Domingos Fernandeo'
 'Cohen, Mr. Gurshon "Gus"' 'Coleff, Mr. Peju' 'Coleff, Mr. Satio'
 'Coleridge, Mr. Reginald Charles' 'Collander, Mr. Erik Gustaf'
 'Colley, Mr. Edward Pomeroy' 'Collyer, Miss. Marjorie "Lottie"'
 'Collyer, Mr. Harvey' 'Collyer, Mrs. Harvey (Charlotte Annie Tate)'
 'Compton, Miss. Sara Rebecca' 'Connaghton, Mr. Michael'
 'Connolly, Miss. Kate' 'Connors, Mr. Patrick' 'Cook, Mr. Jacob'
 'Cor, Mr. Liudevit' 'Corn, Mr. Harry'
 'Coutts, Master. Eden Leslie "Neville"'
 'Coutts, Master. William Loch "William"' 'Coxon, Mr. Daniel'
 'Crease, Mr. Ernest James' 'Cribb, Mr. John Hatfield'
 'Crosby, Capt. Edward Gifford' 'Crosby, Miss. Harriet R'
 'Culumovic, Mr. Jeso'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Cunningham, Mr. Alfred Fleming' 'Dahl, Mr. Karl Edwart'
 'Dahlberg, Miss. Gerda Ulrika' 'Dakic, Mr. Branko'
 'Daly, Mr. Eugene Patrick' 'Daly, Mr. Peter Denis '
 'Danbom, Mr. Ernst Gilbert'
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)'
 'Daniel, Mr. Robert Williams' 'Danoff, Mr. Yoto' 'Dantcheff, Mr. Ristiu'
 'Davidson, Mr. Thornton' 'Davies, Master. John Morgan Jr'
 'Davies, Mr. Alfred J' 'Davies, Mr. Charles Henry' 'Davis, Miss. Mary'
 'Davison, Mrs. Thomas Henry (Mary E Finck)' 'Dean, Master. Bertram Vere'
 'Dean, Mr. Bertram Frank' 'Denkoff, Mr. Mitto' 'Dennis, Mr. Samuel'
 'Devaney, Miss. Margaret Delia' 'Dick, Mr. Albert Adrian'
 'Dick, Mrs. Albert Adrian (Vera Gillespie)' 'Dimic, Mr. Jovan'
 'Dodge, Master. Washington' 'Doharr, Mr. Tannous' 'Doling, Miss. Elsie'
 'Doling, Mrs. John T (Ada Julia Bone)' 'Dooley, Mr. Patrick'
 'Dorking, Mr. Edward Arthur' 'Douglas, Mr. Walter Donald'
 'Dowdell, Miss. Elizabeth' 'Downton, Mr. William James'
 'Drazenoic, Mr. Jozef' 'Drew, Mrs. James Vivian (Lulu Thorne Christian)'
 'Duane, Mr. Frank'
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")'
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")'
 'Duran y More, Miss. Asuncion' 'Edvardsson, Mr. Gustaf Hjalmar'
 'Eitemiller, Mr. George Floyd' 'Eklund, Mr. Hans Linus'
 'Ekstrom, Mr. Johan' 'Elias, Mr. Dibo' 'Elias, Mr. Joseph Jr'
 'Elias, Mr. Tannous' 'Elsbury, Mr. William James'
 'Emanuel, Miss. Virginia Ethel' 'Emir, Mr. Farred Chehab'
 'Endres, Miss. Caroline Louise' 'Eustis, Miss. Elizabeth Mussey'
 'Fahlstrom, Mr. Arne Jonas' 'Farrell, Mr. James' 'Farthing, Mr. John'
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)'
 'Fischer, Mr. Eberhard Thelander' 'Fleming, Miss. Margaret'
 'Flynn, Mr. James' 'Flynn, Mr. John' 'Flynn, Mr. John Irwin ("Irving")'
 'Foo, Mr. Choong' 'Ford, Miss. Doolina Margaret "Daisy"'
 'Ford, Miss. Robina Maggie "Ruby"' 'Ford, Mr. William Neal'
 'Ford, Mrs. Edward (Margaret Ann Watson)'
 'Foreman, Mr. Benjamin Laventall' 'Fortune, Miss. Alice Elizabeth'
 'Fortune, Miss. Mabel Helen' 'Fortune, Mr. Charles Alexander'
 'Fortune, Mr. Mark' 'Fox, Mr. Stanley Hubert'
 'Francatelli, Miss. Laura Mabel' 'Frauenthal, Dr. Henry William'
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)'
 'Frolicher, Miss. Hedwig Margaritha' 'Frolicher-Stehli, Mr. Maxmillian'
 'Frost, Mr. Anthony Wood "Archie"' 'Fry, Mr. Richard'
 'Funk, Miss. Annie Clemmer' 'Futrelle, Mr. Jacques Heath'
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)' 'Fynney, Mr. Joseph J'
 'Gale, Mr. Shadrach' 'Gallagher, Mr. Martin' 'Garfirth, Mr. John'
 'Garside, Miss. Ethel' 'Gaskell, Mr. Alfred' 'Gavey, Mr. Lawrence'
 'Gee, Mr. Arthur H' 'Gheorgheff, Mr. Stanio' 'Giglio, Mr. Victor'
 'Giles, Mr. Frederick Edward' 'Gilinski, Mr. Eliezer'
 'Gill, Mr. John William' 'Gillespie, Mr. William Henry'
 'Gilnagh, Miss. Katherine "Katie"' 'Givard, Mr. Hans Kristensen'
 'Glynn, Miss. Mary Agatha' 'Goldenberg, Mr. Samuel L'
 'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)'
 'Goldschmidt, Mr. George B'
 'Goldsmith, Master. Frank John William "Frankie"'
 'Goldsmith, Mr. Frank John'
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)'
 'Goncalves, Mr. Manuel Estanslas' 'Goodwin, Master. Harold Victor'
 'Goodwin, Master. Sidney Leonard' 'Goodwin, Master. William Frederick'
 'Goodwin, Miss. Lillian Amy' 'Goodwin, Mr. Charles Edward'
 'Goodwin, Mrs. Frederick (Augusta Tyler)' 'Graham, Miss. Margaret Edith'
 'Graham, Mr. George Edward'
 'Graham, Mrs. William Thompson (Edith Junkins)' 'Green, Mr. George Henry'
 'Greenberg, Mr. Samuel' 'Greenfield, Mr. William Bertram'
 'Gronnestad, Mr. Daniel Danielsen' 'Guggenheim, Mr. Benjamin'
 'Gustafsson, Mr. Alfred Ossian' 'Gustafsson, Mr. Anders Vilhelm'
 'Gustafsson, Mr. Johan Birger' 'Gustafsson, Mr. Karl Gideon'
 'Haas, Miss. Aloisia' 'Hagland, Mr. Ingvald Olai Olsen'
 'Hagland, Mr. Konrad Mathias Reiersen' 'Hakkarainen, Mr. Pekka Pietari'
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)'
 'Hale, Mr. Reginald' 'Hamalainen, Master. Viljo'
 'Hamalainen, Mrs. William (Anna)' 'Hampe, Mr. Leon' 'Hanna, Mr. Mansour'
 'Hansen, Mr. Claus Peter' 'Hansen, Mr. Henrik Juul'
 'Hansen, Mr. Henry Damsgaard' 'Harder, Mr. George Achilles'
 'Harknett, Miss. Alice Phoebe' 'Harmer, Mr. Abraham (David Lishin)'
 'Harper, Miss. Annie Jessie "Nina"' 'Harper, Mr. Henry Sleeper'
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)' 'Harper, Rev. John'
 'Harrington, Mr. Charles H' 'Harris, Mr. George'
 'Harris, Mr. Henry Birkhardt' 'Harris, Mr. Walter'
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)' 'Harrison, Mr. William'
 'Hart, Miss. Eva Miriam' 'Hart, Mr. Benjamin' 'Hart, Mr. Henry'
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)' 'Hassab, Mr. Hammad'
 'Hassan, Mr. Houssein G N' 'Hawksford, Mr. Walter James'
 'Hays, Miss. Margaret Bechstein'
 'Hays, Mrs. Charles Melville (Clara Jennings Gregg)'
 'Healy, Miss. Hanora "Nora"' 'Hedman, Mr. Oskar Arvid'
 'Hegarty, Miss. Hanora "Nora"' 'Heikkinen, Miss. Laina'
 'Heininen, Miss. Wendla Maria' 'Hendekovic, Mr. Ignjac'
 'Henry, Miss. Delia' 'Herman, Miss. Alice'
 'Herman, Mrs. Samuel (Jane Laver)' 'Hewlett, Mrs. (Mary D Kingcome) '
 'Hickman, Mr. Leonard Mark' 'Hickman, Mr. Lewis'
 'Hickman, Mr. Stanley George' 'Hippach, Miss. Jean Gertrude'
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)'
 'Hirvonen, Miss. Hildur E' 'Hocking, Mr. Richard George'
 'Hocking, Mrs. Elizabeth (Eliza Needs)' 'Hodges, Mr. Henry Price'
 'Hogeboom, Mrs. John C (Anna Andrews)' 'Hold, Mr. Stephen'
 'Holm, Mr. John Fredrik Alexander' 'Holverson, Mr. Alexander Oskar'
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)'
 'Homer, Mr. Harry ("Mr E Haven")' 'Honkanen, Miss. Eliina'
 'Hood, Mr. Ambrose Jr' 'Horgan, Mr. John' 'Hosono, Mr. Masabumi'
 'Hoyt, Mr. Frederick Maxfield' 'Hoyt, Mr. William Fisher'
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)'
 'Humblen, Mr. Adolf Mathias Nicolai Olsen' 'Hunt, Mr. George Henry'
 'Ibrahim Shawah, Mr. Yousseff' 'Icard, Miss. Amelie'
 'Ilett, Miss. Bertha' 'Ilmakangas, Miss. Pieta Sofia'
 'Isham, Miss. Ann Elizabeth' 'Ivanoff, Mr. Kanio'
 'Jacobsohn, Mr. Sidney Samuel'
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)'
 'Jalsevac, Mr. Ivan' 'Jansson, Mr. Carl Olof' 'Jardin, Mr. Jose Neto'
 'Jarvis, Mr. John Denzil' 'Jenkin, Mr. Stephen Curnow'
 'Jensen, Mr. Hans Peder' 'Jensen, Mr. Niels Peder'
 'Jensen, Mr. Svend Lauritz' 'Jermyn, Miss. Annie'
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)'
 'Johannesen-Bratthammer, Mr. Bernt' 'Johanson, Mr. Jakob Alfred'
 'Johansson, Mr. Erik' 'Johansson, Mr. Gustaf Joel'
 'Johansson, Mr. Karl Johan' 'Johnson, Master. Harold Theodor'
 'Johnson, Miss. Eleanor Ileen' 'Johnson, Mr. Alfred'
 'Johnson, Mr. Malkolm Joackim' 'Johnson, Mr. William Cahoone Jr'
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
 'Johnston, Miss. Catherine Helen "Carrie"' 'Johnston, Mr. Andrew G'
 'Jonkoff, Mr. Lalio' 'Jonsson, Mr. Carl' 'Jussila, Miss. Katriina'
 'Jussila, Miss. Mari Aina' 'Jussila, Mr. Eiriik'
 'Kallio, Mr. Nikolai Erland' 'Kalvik, Mr. Johannes Halvorsen'
 'Kantor, Mr. Sinai' 'Kantor, Mrs. Sinai (Miriam Sternin)'
 'Karaic, Mr. Milan' 'Karlsson, Mr. Nils August' 'Karun, Miss. Manca'
 'Kassem, Mr. Fared' 'Keane, Miss. Nora A' 'Keane, Mr. Andrew "Andy"'
 'Keefe, Mr. Arthur' 'Kelly, Miss. Anna Katherine "Annie Kate"'
 'Kelly, Miss. Mary' 'Kelly, Mr. James' 'Kelly, Mrs. Florence "Fannie"'
 'Kent, Mr. Edward Austin' 'Kenyon, Mrs. Frederick R (Marion)'
 'Kiernan, Mr. Philip' 'Kilgannon, Mr. Thomas J'
 'Kimball, Mr. Edwin Nelson Jr' 'Kink, Mr. Vincenz'
 'Kink-Heilmann, Miss. Luise Gretchen' 'Kirkland, Rev. Charles Leonard'
 'Klaber, Mr. Herman' 'Klasen, Mr. Klas Albin' 'Knight, Mr. Robert J'
 'Kraeff, Mr. Theodor' 'Kvillner, Mr. Johan Henrik Johannesson'
 'Lahoud, Mr. Sarkis' 'Lahtinen, Mrs. William (Anna Sylfven)'
 'Laitinen, Miss. Kristina Sofia' 'Laleff, Mr. Kristo' 'Lam, Mr. Ali'
 'Lam, Mr. Len' 'Landergren, Miss. Aurora Adelia' 'Lang, Mr. Fang'
 'Laroche, Miss. Simonne Marie Anne Andree'
 'Laroche, Mr. Joseph Philippe Lemercier'
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)'
 'Larsson, Mr. August Viktor' 'Larsson, Mr. Bengt Edvin'
 'LeRoy, Miss. Bertha' 'Leader, Dr. Alice (Farnham)'
 'Leeni, Mr. Fahim ("Philip Zenni")' 'Lefebre, Master. Henry Forbes'
 'Lefebre, Miss. Ida' 'Lefebre, Miss. Jeannie' 'Lefebre, Miss. Mathilde'
 'Lehmann, Miss. Bertha' 'Leinonen, Mr. Antti Gustaf'
 'Leitch, Miss. Jessie Wills' 'Lemberopolous, Mr. Peter L'
 'Lemore, Mrs. (Amelia Milley)' 'Lennon, Mr. Denis' 'Leonard, Mr. Lionel'
 'Lester, Mr. James' 'Lesurer, Mr. Gustave J' 'Levy, Mr. Rene Jacques'
 'Lewy, Mr. Ervin G' 'Leyson, Mr. Robert William Norman'
 'Lievens, Mr. Rene Aime' 'Lindahl, Miss. Agda Thorilda Viktoria'
 'Lindblom, Miss. Augusta Charlotta' 'Lindell, Mr. Edvard Bengtsson'
 'Lindqvist, Mr. Eino William' 'Lines, Miss. Mary Conover' 'Ling, Mr. Lee'
 'Lobb, Mr. William Arthur'
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)'
 'Long, Mr. Milton Clyde' 'Longley, Miss. Gretchen Fiske'
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)'
 'Lovell, Mr. John Hall ("Henry")' 'Lulic, Mr. Nikola'
 'Lundahl, Mr. Johan Svensson' 'Lurette, Miss. Elise' 'Mack, Mrs. (Mary)'
 'Madigan, Miss. Margaret "Maggie"' 'Madill, Miss. Georgette Alexandra'
 'Madsen, Mr. Fridtjof Arne' 'Maenpaa, Mr. Matti Alexanteri'
 'Maioni, Miss. Roberta' 'Maisner, Mr. Simon' 'Mallet, Master. Andre'
 'Mallet, Mr. Albert' 'Mamee, Mr. Hanna' 'Mangan, Miss. Mary'
 'Mannion, Miss. Margareth' 'Marechal, Mr. Pierre' 'Markoff, Mr. Marin'
 'Markun, Mr. Johann' 'Marvin, Mr. Daniel Warner'
 'Masselmani, Mrs. Fatima' 'Matthews, Mr. William John'
 'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")'
 'McCarthy, Mr. Timothy J' 'McCormack, Mr. Thomas Joseph'
 'McCoy, Miss. Agnes' 'McCoy, Mr. Bernard'
 'McDermott, Miss. Brigdet Delia' 'McEvoy, Mr. Michael'
 'McGough, Mr. James Robert' 'McGovern, Miss. Mary'
 'McGowan, Miss. Anna "Annie"' 'McKane, Mr. Peter David'
 'McMahon, Mr. Martin' 'McNamee, Mr. Neal'
 'Meanwell, Miss. (Marion Ogden)'
 'Meek, Mrs. Thomas (Annie Louise Rowley)'
 'Mellinger, Miss. Madeleine Violet'
 'Mellinger, Mrs. (Elizabeth Anne Maidment)' 'Mellors, Mr. William John'
 'Meo, Mr. Alfonzo' 'Mernagh, Mr. Robert' 'Meyer, Mr. August'

In [29]:
for i in df1.columns:
  print(i,df1[i].sort_values().unique(),"\n",sep="\n")

PassengerId
[ 892  893  894  895  896  897  898  899  900  901  902  903  904  905
  906  907  908  909  910  911  912  913  914  915  916  917  918  919
  920  921  922  923  924  925  926  927  928  929  930  931  932  933
  934  935  936  937  938  939  940  941  942  943  944  945  946  947
  948  949  950  951  952  953  954  955  956  957  958  959  960  961
  962  963  964  965  966  967  968  969  970  971  972  973  974  975
  976  977  978  979  980  981  982  983  984  985  986  987  988  989
  990  991  992  993  994  995  996  997  998  999 1000 1001 1002 1003
 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017
 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031
 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045
 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059
 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073
 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085 1086 1087
 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099 1100 1101
 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112 1113 1114 1115
 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126 1127 1128 1129
 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140 1141 1142 1143
 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154 1155 1156 1157
 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168 1169 1170 1171
 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185
 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199
 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213
 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224 1225 1226 1227
 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238 1239 1240 1241
 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252 1253 1254 1255
 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266 1267 1268 1269
 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280 1281 1282 1283
 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294 1295 1296 1297
 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308 1309]


Pclass
[1 2 3]


Name
['Abbott, Master. Eugene Joseph' 'Abelseth, Miss. Karen Marie'
 'Abelseth, Mr. Olaus Jorgensen'
 'Abrahamsson, Mr. Abraham August Johannes'
 'Abrahim, Mrs. Joseph (Sophie Halaut Easu)' 'Aks, Master. Philip Frank'
 'Aldworth, Mr. Charles Augustus' 'Allison, Mr. Hudson Joshua Creighton'
 'Andersen, Mr. Albert Karvin' 'Andersson, Miss. Ida Augusta Margareta'
 'Andersson, Mr. Johan Samuel' 'Andrew, Mr. Frank Thomas'
 'Angheloff, Mr. Minko' 'Angle, Mr. William A'
 'Aronsson, Mr. Ernst Axel Algot' 'Ashby, Mr. John'
 'Asplund, Master. Carl Edgar' 'Asplund, Master. Filip Oscar'
 'Asplund, Mr. Carl Oscar Vilhelm Gustafsson' 'Asplund, Mr. Johan Charles'
 'Assaf Khalil, Mrs. Mariana (Miriam")"' 'Assaf, Mr. Gerios'
 'Assam, Mr. Ali' 'Astor, Col. John Jacob' 'Baccos, Mr. Raffull'
 'Badman, Miss. Emily Louisa' 'Baimbrigge, Mr. Charles Robert'
 'Barry, Miss. Julia' 'Beattie, Mr. Thomson' 'Beauchamp, Mr. Henry James'
 'Becker, Miss. Ruth Elizabeth'
 'Becker, Mrs. Allen Oliver (Nellie E Baumgardner)'
 'Bentham, Miss. Lilian W' 'Betros, Master. Seman' 'Bird, Miss. Ellen'
 'Birnbaum, Mr. Jakob' 'Bjorklund, Mr. Ernst Herbert'
 'Bonnell, Miss. Caroline' 'Borebank, Mr. John James'
 'Botsford, Mr. William Hull' 'Boulos, Master. Akar'
 'Bowen, Miss. Grace Scott' 'Bowenur, Mr. Solomon'
 'Bradley, Miss. Bridget Delia' 'Brady, Mr. John Bertram'
 'Braf, Miss. Elin Ester Maria' 'Brandeis, Mr. Emil'
 'Brobeck, Mr. Karl Rudolf' 'Brown, Miss. Edith Eileen'
 'Brown, Mrs. John Murray (Caroline Lane Lamson)'
 'Bryhl, Miss. Dagmar Jenny Ingeborg ' 'Buckley, Miss. Katherine'
 'Buckley, Mr. Daniel' 'Bucknell, Mrs. William Robert (Emma Eliza Ward)'
 'Burns, Miss. Mary Delia' 'Cacic, Miss. Manda' 'Cacic, Mr. Jego Grga'
 'Caldwell, Mr. Albert Francis' 'Canavan, Mr. Patrick'
 'Candee, Mrs. Edward (Helen Churchill Hungerford)' 'Caram, Mr. Joseph'
 'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)'
 'Carlsson, Mr. Carl Robert' 'Carr, Miss. Jeannie'
 'Carrau, Mr. Jose Pedro' 'Carver, Mr. Alfred John'
 'Case, Mr. Howard Brown'
 'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)'
 'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)'
 'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)'
 'Chapman, Mrs. John Henry (Sara Elizabeth Lawry)'
 'Chaudanson, Miss. Victorine' 'Chevre, Mr. Paul Romaine'
 'Chisholm, Mr. Roderick Robert Crispin' 'Christy, Mrs. (Alice Frances)'
 'Chronopoulos, Mr. Demetrios' 'Clark, Mr. Walter Miller'
 'Clark, Mrs. Walter Miller (Virginia McDowell)'
 'Clarke, Mr. Charles Valentine' 'Colbert, Mr. Patrick'
 'Collett, Mr. Sidney C Stuart' 'Compton, Mr. Alexander Taylor Jr'
 'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)'
 'Conlon, Mr. Thomas Henry' 'Connolly, Miss. Kate'
 'Cook, Mrs. (Selena Rogers)' 'Cor, Mr. Bartol' 'Cor, Mr. Ivan'
 'Corbett, Mrs. Walter H (Irene Colvin)'
 'Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)'
 'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)'
 'Cotterill, Mr. Henry Harry""'
 'Coutts, Mrs. William (Winnie Minnie" Treanor)"'
 'Crafton, Mr. John Bertram' 'Cribb, Miss. Laura Alice'
 'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)'
 'Cumings, Mr. John Bradley' 'Daher, Mr. Shedid'
 'Daly, Miss. Margaret Marcella Maggie""'
 'Danbom, Master. Gilbert Sigvard Emanuel' 'Daniels, Miss. Sarah'
 'Davidson, Mrs. Thornton (Orian Hays)' 'Davies, Mr. Evan'
 'Davies, Mr. John Samuel' 'Davies, Mr. Joseph'
 'Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) '
 'Davison, Mr. Thomas Henry' 'Deacon, Mr. Percy William'
 'Dean, Miss. Elizabeth Gladys Millvina""'
 'Dean, Mrs. Bertram (Eva Georgetta Light)' 'Delalic, Mr. Redjo'
 'Demetri, Mr. Marinko' 'Denbury, Mr. Herbert' 'Dennis, Mr. William'
 'Dibden, Mr. William' 'Dika, Mr. Mirko' 'Dintcheff, Mr. Valtcho'
 'Dodge, Dr. Washington' 'Dodge, Mrs. Washington (Ruth Vidaver)'
 'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)'
 'Douglas, Mrs. Walter Donald (Mahala Dutton)' 'Doyle, Miss. Elizabeth'
 'Drapkin, Miss. Jennie' 'Drew, Master. Marshall Brines'
 'Drew, Mr. James Vivian' 'Dulles, Mr. William Crothers'
 'Duquemin, Mr. Joseph' 'Duran y More, Miss. Florentina'
 'Dyker, Mr. Adolf Fredrik'
 'Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)'
 'Earnshaw, Mrs. Boulton (Olive Potter)' 'Elias, Mr. Joseph'
 'Enander, Mr. Ingvar' 'Evans, Miss. Edith Corse'
 'Everett, Mr. Thomas James' 'Faunthorpe, Mr. Harry'
 'Fillbrook, Mr. Joseph Charles' 'Finoli, Mr. Luigi'
 'Flegenheim, Mrs. Alfred (Antoinette)' 'Fleming, Miss. Honora'
 'Foley, Mr. Joseph' 'Foley, Mr. William' 'Ford, Mr. Arthur'
 'Ford, Mr. Edward Watson' 'Fortune, Miss. Ethel Flora'
 'Fortune, Mrs. Mark (Mary McDougald)' 'Fox, Mr. Patrick'
 'Franklin, Mr. Charles (Charles Fardon)' 'Franklin, Mr. Thomas Parham'
 'Frauenthal, Mr. Isaac Gerald'
 'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)'
 'Gale, Mr. Harry' 'Geiger, Miss. Amalie' 'Gibson, Miss. Dorothy Winifred'
 'Gibson, Mrs. Leonard (Pauline C Boeson)' 'Gilbert, Mr. William'
 'Giles, Mr. Edgar' 'Giles, Mr. Ralph' 'Goldsmith, Mr. Nathan'
 'Goodwin, Miss. Jessie Allis' 'Goodwin, Mr. Charles Frederick'
 'Gracie, Col. Archibald IV'
 'Greenfield, Mrs. Leo David (Blanche Strouse)' 'Guest, Mr. Robert'
 'Hagardon, Miss. Kate' 'Hansen, Mrs. Claus Peter (Jennie L Howard)'
 'Harbeck, Mr. William H' 'Harder, Mrs. George Achilles (Dorothy Annan)'
 'Hays, Mr. Charles Melville' 'Head, Mr. Christopher' 'Hee, Mr. Ling'
 'Hellstrom, Miss. Hilda Maria' 'Henriksson, Miss. Jenny Lovisa'
 'Herman, Miss. Kate' 'Herman, Mr. Samuel' 'Hilliard, Mr. Herbert Henry'
 'Hiltunen, Miss. Marta' 'Hipkins, Mr. William Edward'
 'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'
 'Hocking, Miss. Ellen Nellie""' 'Hocking, Mr. Samuel James Metcalfe'
 'Hold, Mrs. Stephen (Annie Margaret Hill)' 'Holthen, Mr. Johan Martin'
 'Howard, Miss. May Elizabeth' 'Howard, Mr. Benjamin'
 'Howard, Mrs. Benjamin (Ellen Truelove Arman)' 'Hyman, Mr. Abraham'
 'Ilieff, Mr. Ylio' 'Ilmakangas, Miss. Ida Livija'
 'Ismay, Mr. Joseph Bruce' 'Jefferys, Mr. Clifford Thomas'
 'Jefferys, Mr. Ernest Wilfred' 'Johansson Palmquist, Mr. Oskar Leander'
 'Johansson, Mr. Nils' 'Johnston, Master. William Arthur Willie""'
 'Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"'
 'Jones, Mr. Charles Cresson' 'Jonsson, Mr. Nils Hilding'
 'Julian, Mr. Henry Forbes' 'Karlsson, Mr. Einar Gervasius'
 'Karlsson, Mr. Julius Konrad Eugen'
 'Karnes, Mrs. J Frank (Claire Bennett)' 'Karun, Mr. Franz'
 'Katavelas, Mr. Vassilios (Catavelas Vassilios")"' 'Keane, Mr. Daniel'
 'Keeping, Mr. Edwin' 'Kelly, Mr. James' 'Kennedy, Mr. John'
 'Kenyon, Mr. Frederick R' 'Khalil, Mr. Betros'
 'Khalil, Mrs. Betros (Zahie Maria" Elias)"' 'Kiernan, Mr. John'
 'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)' 'Kink, Miss. Maria'
 'Kink-Heilmann, Mr. Anton' 'Kink-Heilmann, Mrs. Anton (Luise Heilmann)'
 'Klasen, Miss. Gertrud Emilia'
 'Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)' 'Krekorian, Mr. Neshan'
 'Kreuchen, Miss. Emilie' 'Lahtinen, Rev. William' 'Lamb, Mr. John Joseph'
 'Lane, Mr. Patrick' 'Laroche, Miss. Louise'
 'Larsson-Rondberg, Mr. Edvard A' 'Lefebre, Mrs. Frank (Frances)'
 'Lennon, Miss. Mary'
 'Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey")"'
 'Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)'
 'Lindstrom, Mrs. Carl Johan (Sigrid Posse)' 'Linehan, Mr. Michael'
 'Lines, Mrs. Ernest H (Elizabeth Lindsey James)' 'Lingane, Mr. John'
 'Lithman, Mr. Simon' 'Lockyer, Mr. Edward' 'Loring, Mr. Joseph Holland'
 'Louch, Mr. Charles Alexander' 'Lundin, Miss. Olga Elida'
 'Lundstrom, Mr. Thure Edvin' 'Lyntakoff, Mr. Stanko'
 'MacKay, Mr. George William' 'Maguire, Mr. John Edward'
 'Mahon, Miss. Bridget Delia' 'Mahon, Mr. John'
 'Makinen, Mr. Kalle Edvard' 'Malachard, Mr. Noel'
 'Mallet, Mrs. Albert (Antoinette Magnin)'
 'Mangiavacchi, Mr. Serafino Emilio' 'Mardirosian, Mr. Sarkis'
 'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)'
 'Matinoff, Mr. Nicola' 'Maybery, Mr. Frank Hubert'
 'McCaffry, Mr. Thomas Francis' 'McCarthy, Miss. Catherine Katie""'
 'McCoy, Miss. Alicia' 'McCrae, Mr. Arthur Gordon'
 'McCrie, Mr. James Matthew' 'McGowan, Miss. Katherine'
 "McNamee, Mrs. Neal (Eileen O'Leary)" 'McNeill, Miss. Bridget'
 'Midtsjo, Mr. Karl Albert' 'Miles, Mr. Frank'
 'Minahan, Mrs. William Edward (Lillian E Thorpe)' 'Minkoff, Mr. Lazar'
 'Mock, Mr. Philipp Edmund' 'Moore, Mr. Clarence Bloomfield'
 'Moubarek, Mrs. George (Omine Amenia" Alexander)"'
 'Mulvihill, Miss. Bertha E' 'Murphy, Miss. Nora'
 'Myles, Mr. Thomas Francis' 'Nakid, Mrs. Said (Waika Mary" Mowad)"'
 'Nancarrow, Mr. William Henry' 'Nasr, Mr. Mustafa'
 'Naughton, Miss. Hannah' 'Nesson, Mr. Israel'
 'Nieminen, Miss. Manta Josefina' 'Niklasson, Mr. Samuel'
 'Nilsson, Miss. Berta Olivia' 'Nilsson, Mr. August Ferdinand'
 'Nourney, Mr. Alfred (Baron von Drachstedt")"' "O'Connor, Mr. Patrick"
 "O'Donoghue, Ms. Bridget" "O'Keefe, Mr. Patrick"
 'Oliva y Ocana, Dona. Fermina' 'Olsen, Master. Artur Karl'
 'Olsson, Mr. Oscar Wilhelm' 'Omont, Mr. Alfred Fernand'
 'Oreskovic, Miss. Jelka' 'Ostby, Miss. Helene Ragnhild'
 'Ovies y Rodriguez, Mr. Servando' 'Oxenham, Mr. Percy Thomas'
 'Pallas y Castello, Mr. Emilio' 'Palsson, Master. Paul Folke'
 'Parker, Mr. Clifford Richard' 'Payne, Mr. Vivian Ponsonby'
 'Peacock, Master. Alfred Edward' 'Peacock, Miss. Treasteall'
 'Peacock, Mrs. Benjamin (Edith Nile)' 'Pearce, Mr. Ernest'
 'Pedersen, Mr. Olaf' 'Peltomaki, Mr. Nikolai Johannes'
 'Peruschitz, Rev. Joseph Maria' 'Peter, Master. Michael J'
 'Petersen, Mr. Marius' 'Phillips, Miss. Alice Frances Louisa'
 'Phillips, Mr. Escott Robert' 'Pokrnic, Mr. Mate' 'Pokrnic, Mr. Tome'
 'Portaluppi, Mr. Emilio Ilario Giuseppe' 'Pulbaum, Mr. Franz'
 'Quick, Miss. Winifred Vera' 'Rasmussen, Mrs. (Lena Jacobsen Solvang)'
 'Reynolds, Mr. Harold J' 'Rheims, Mr. George Alexander Lucien'
 'Rice, Master. Albert' 'Riihivouri, Miss. Susanna Juhantytar Sanni""'
 'Riordan, Miss. Johanna Hannah""' 'Risien, Mrs. Samuel (Emma)'
 'Robins, Mr. Alexander A' 'Rogers, Mr. Reginald Harry'
 'Rosblom, Miss. Salli Helena' 'Rosenbaum, Miss. Edith Louise'
 'Rosenshine, Mr. George (Mr George Thorne")"' 'Roth, Miss. Sarah A'
 'Rothschild, Mr. Martin' 'Rowe, Mr. Alfred G' 'Ryan, Mr. Edward'
 'Ryerson, Master. John Borie' 'Ryerson, Mr. Arthur Larned'
 'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)' 'Saade, Mr. Jean Nassr'
 'Sadowitz, Mr. Harry' 'Saether, Mr. Simon Sivertsen'
 'Sage, Master. William Henry' 'Sage, Miss. Ada' 'Sage, Mr. John George'
 'Sage, Mrs. John (Annie Bullen)' 'Salander, Mr. Karl Johan'
 'Salomon, Mr. Abraham L' 'Samaan, Mr. Elias' 'Samaan, Mr. Hanna'
 'Sandstrom, Miss. Beatrice Irene' 'Sap, Mr. Julius'
 'Schabert, Mrs. Paul (Emma Mock)' 'Schmidt, Mr. August'
 'Shaughnessy, Mr. Patrick' 'Shine, Miss. Ellen Natalia'
 'Sincock, Miss. Maude' 'Smith, Mr. Lucien Philip'
 'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)' 'Smyth, Miss. Julia'
 'Snyder, Mr. John Pillsbury'
 'Snyder, Mrs. John Pillsbury (Nelle Stevenson)' 'Spector, Mr. Woolf'
 'Spedden, Master. Robert Douglas' 'Spedden, Mr. Frederic Oakley'
 'Spencer, Mr. William Augustus' 'Spinner, Mr. Henry John'
 'Stanton, Mr. Samuel Ward' 'Stengel, Mr. Charles Emil Henry'
 'Stengel, Mrs. Charles Emil Henry (Annie May Morris)'
 'Stokes, Mr. Philip Joseph' 'Storey, Mr. Thomas' 'Straus, Mr. Isidor'
 'Straus, Mrs. Isidor (Rosalie Ida Blun)' 'Strilic, Mr. Ivan'
 'Svensson, Mr. Johan Cervin' 'Swane, Mr. George'
 'Sweet, Mr. George Frederick' 'Tenglin, Mr. Gunnar Isidor'
 'Thomas, Mr. Charles P' 'Thomas, Mr. John' 'Thomas, Mr. Tannous'
 'Thomas, Mrs. Alexander (Thamine Thelma")"'
 'Thomson, Mr. Alexander Morrison' 'Torfa, Mr. Assad'
 'Touma, Master. Georges Youssef' 'Touma, Miss. Maria Youssef'
 'Tucker, Mr. Gilbert Milligan Jr' 'Vander Planke, Mr. Julius'
 'Vartanian, Mr. David' 'Veal, Mr. James' 'Vendel, Mr. Olof Edvin'
 'Walcroft, Miss. Nellie' 'Ware, Mr. Frederick' 'Ware, Mr. John James'
 'Ware, Mr. William Jeffery'
 'Ware, Mrs. John James (Florence Louise Long)'
 'Warren, Mr. Charles William' 'Warren, Mr. Frank Manley'
 'Watt, Miss. Bertha J' 'Weisz, Mr. Leopold' 'Wells, Master. Ralph Lester'
 'Wells, Mrs. Arthur Henry (Addie" Dart Trevaskis)"' 'Wenzel, Mr. Linhart'
 'West, Miss. Barbara J' 'Whabee, Mrs. George Joseph (Shawneene Abi-Saab)'
 'Wheeler, Mr. Edwin Frederick""' 'White, Mrs. John Stuart (Ella Holmes)'
 'Wick, Mr. George Dennick' 'Widener, Mr. George Dunton'
 'Widener, Mrs. George Dunton (Eleanor Elkins)' 'Wiklund, Mr. Karl Johan'
 'Wilkes, Mrs. James (Ellen Needs)' 'Willard, Miss. Constance'
 'Willer, Mr. Aaron (Abi Weller")"' 'Williams, Mr. Richard Norris II'
 'Wilson, Miss. Helen Alice' 'Wirz, Mr. Albert'
 'Wittevrongel, Mr. Camille' 'Wright, Miss. Marion'
 'Zakarian, Mr. Mapriededer' 'Zakarian, Mr. Ortin'
 'de Brito, Mr. Jose Joaquim' 'de Messemaeker, Mr. Guillaume Joseph'
 'del Carlo, Mrs. Sebastiano (Argenia Genovesi)'
 'van Billiard, Master. James William' 'van Billiard, Master. Walter John']


Sex
['female' 'male']


Age
[ 0.17        0.33        0.75        0.83        0.92        1.
  2.          3.          5.          6.          7.          8.
  9.         10.         11.5        12.         13.         14.
 14.5        15.         16.         17.         18.         18.5
 19.         20.         21.         22.         22.5        23.
 24.         25.         26.         26.5        27.         28.
 28.5        29.         30.         30.27259036 31.         32.
 32.5        33.         34.         34.5        35.         36.
 36.5        37.         38.         38.5        39.         40.
 40.5        41.         42.         43.         44.         45.
 46.         47.         48.         49.         50.         51.
 53.         54.         55.         57.         58.         59.
 60.         60.5        61.         62.         63.         64.
 67.         76.        ]


SibSp
[0 1 2 3 4 5 8]


Parch
[0 1 2 3 4 5 6 9]


Ticket
['110469' '110489' '110813' '111163' '112051' '112058' '112377' '112378'
 '112901' '113038' '113044' '113054' '113059' '113503' '113509' '113773'
 '113778' '113780' '113781' '113790' '113791' '113795' '113796' '113801'
 '11753' '11765' '11767' '11769' '11770' '11778' '11813' '1222' '12749'
 '13050' '13236' '13508' '13567' '13695' '13905' '1601' '16966' '17463'
 '17464' '17475' '17765' '17770' '19877' '19924' '19928' '19950' '2003'
 '211535' '21228' '21332' '220844' '220845' '226875' '228414' '230136'
 '233478' '233734' '235509' '236853' '236854' '237216' '237249' '237393'
 '237670' '237734' '237735' '237789' '239059' '240261' '240276' '24065'
 '24160' '242963' '244346' '244358' '244360' '244368' '248659' '248726'
 '248734' '248738' '248744' '248746' '250650' '250651' '2543' '2621'
 '2622' '2625' '26360' '2650' '2652' '2653' '2654' '2655' '2656' '2657'
 '2658' '2660' '2661' '2662' '2668' '2670' '26707' '2673' '2675' '2676'
 '2678' '2679' '2680' '2681' '2682' '2684' '2688' '2689' '2692' '2696'
 '2698' '28004' '28034' '28133' '28220' '28221' '28404' '28664' '28666'
 '29103' '29105' '29107' '2926' '29750' '3101266' '3101295' '3101297'
 '3101298' '315083' '315085' '315087' '315091' '315092' '315095' '315152'
 '315153' '315154' '32302' '329944' '330844' '330910' '330911' '330920'
 '330924' '330963' '330968' '330971' '330972' '334914' '334915' '335432'
 '33638' '3410' '342441' '342684' '342712' '343271' '345498' '345501'
 '345572' '345763' '345768' '345771' '345775' '3470' '347065' '347066'
 '347070' '347072' '347075' '347077' '347079' '347080' '347086' '347090'
 '347091' '347465' '347467' '347469' '347471' '348122' '348125' '349202'
 '349211' '349220' '349226' '349229' '349230' '349232' '349235' '349238'
 '349250' '349255' '349256' '349909' '349910' '349911' '350026' '350033'
 '350045' '350053' '350054' '350403' '350405' '350408' '350409' '350410'
 '350416' '359306' '359309' '363272' '363611' '364498' '364856' '364858'
 '364859' '365235' '365237' '36568' '366713' '367226' '367227' '368364'
 '368402' '368573' '368702' '368783' '36928' '3701' '370129' '370368'
 '370371' '370374' '371109' '371362' '376563' '376566' '382650' '382652'
 '382653' '383123' '383162' '386525' '392091' '392095' '4133' '65305'
 '680' '694' '7266' '7538' '7548' '7935' '9232' 'A. 2. 39186' 'A./5. 3338'
 'A.5. 3236' 'A/4 31416' 'A/4 48871' 'A/4 48873' 'A/5 1478' 'A/5 21175'
 'A/5. 3337' 'A/5. 851' 'AQ/3. 30631' 'AQ/4 3130' 'C 17368' 'C 4001'
 'C.A. 15185' 'C.A. 2315' 'C.A. 2673' 'C.A. 30769' 'C.A. 31029'
 'C.A. 31030' 'C.A. 33112' 'C.A. 33595' 'C.A. 34050' 'C.A. 34644'
 'C.A. 34651' 'C.A. 37671' 'C.A. 42795' 'C.A. 49867' 'C.A. 6212' 'CA 2144'
 'CA 31352' 'CA. 2343' 'F.C. 12750' 'F.C. 12998' 'F.C.C. 13528'
 'F.C.C. 13534' 'F.C.C. 13540' 'LP 1588' 'PC 17483' 'PC 17531' 'PC 17558'
 'PC 17562' 'PC 17569' 'PC 17580' 'PC 17585' 'PC 17591' 'PC 17592'
 'PC 17594' 'PC 17597' 'PC 17598' 'PC 17599' 'PC 17603' 'PC 17606'
 'PC 17607' 'PC 17608' 'PC 17613' 'PC 17755' 'PC 17756' 'PC 17757'
 'PC 17758' 'PC 17759' 'PC 17760' 'PC 17761' 'PP 9549' 'S.C./PARIS 2079'
 'S.O./P.P. 2' 'S.O./P.P. 251' 'S.O./P.P. 752' 'S.O.C. 14879' 'SC 14888'
 'SC/A.3 2861' 'SC/A4 23568' 'SC/AH 29037' 'SC/AH 3085' 'SC/PARIS 2147'
 'SC/PARIS 2148' 'SC/PARIS 2159' 'SC/PARIS 2166' 'SC/PARIS 2167'
 'SC/PARIS 2168' 'SC/Paris 2123' 'SOTON/O.Q. 3101262' 'SOTON/O.Q. 3101263'
 'SOTON/O.Q. 3101308' 'SOTON/O.Q. 3101309' 'SOTON/O.Q. 3101314'
 'SOTON/O.Q. 3101315' 'SOTON/O2 3101284' 'SOTON/OQ 392083'
 'STON/O 2. 3101268' 'STON/O 2. 3101291' 'STON/O2. 3101270'
 'STON/OQ. 369943' 'W./C. 14260' 'W./C. 14266' 'W./C. 6607' 'W./C. 6608'
 'W.E.P. 5734']


Fare
[  0.       3.1708   6.4375   6.4958   6.95     7.       7.05     7.225
   7.2292   7.25     7.2833   7.55     7.575    7.5792   7.6292   7.65
   7.7208   7.725    7.7333   7.75     7.775    7.7792   7.7958   7.8208
   7.8292   7.85     7.8542   7.8792   7.8875   7.8958   7.925    8.05

In [30]:
for i in df2.columns:
  print(i,df2[i].sort_values().unique(),"\n",sep="\n")

PassengerId
[ 892  893  894  895  896  897  898  899  900  901  902  903  904  905
  906  907  908  909  910  911  912  913  914  915  916  917  918  919
  920  921  922  923  924  925  926  927  928  929  930  931  932  933
  934  935  936  937  938  939  940  941  942  943  944  945  946  947
  948  949  950  951  952  953  954  955  956  957  958  959  960  961
  962  963  964  965  966  967  968  969  970  971  972  973  974  975
  976  977  978  979  980  981  982  983  984  985  986  987  988  989
  990  991  992  993  994  995  996  997  998  999 1000 1001 1002 1003
 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017
 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031
 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045
 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059
 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073
 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085 1086 1087
 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099 1100 1101
 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112 1113 1114 1115
 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126 1127 1128 1129
 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140 1141 1142 1143
 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154 1155 1156 1157
 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168 1169 1170 1171
 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185
 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199
 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213
 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224 1225 1226 1227
 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238 1239 1240 1241
 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252 1253 1254 1255
 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266 1267 1268 1269
 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280 1281 1282 1283
 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294 1295 1296 1297
 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308 1309]


Survived
[0 1]

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,28.566970,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.199572,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,24.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df1.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  418.000000  418.000000  418.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.560497
std     120.810458    0.841838   12.634534    0.896760    0.981429   55.857145
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   23.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   30.272590    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   35.750000    1.000000    0.000000   31.471875
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [ ]:
df2.describe()

       PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [ ]:
#Remove outliers
num=[]
for i in num:
  q1=df[i].quantile(0.25)
  q3=df[i].quantile(0.75)
  iqr=q3-q1
  ul=q3+1.5*iqr
  ll=q1-1.5*iqr
  df=df[(df[i] < ul) & (df[i]>ll)]

In [ ]:
num=[]
for i in num:
  q1=df[i].quantile(0.25)
  q3=df[i].quantile(0.75)
  iqr=q3-q1
  ul=q3+1.5*iqr
  ll=q1-1.5*iqr
  df1=df1[(df1[i] < ul) & (df1[i]>ll)]

In [ ]:
num=[]
for i in num:
  q1=df[i].quantile(0.25)
  q3=df[i].quantile(0.75)
  iqr=q3-q1
  ul=q3+1.5*iqr
  ll=q1-1.5*iqr
  df2=df2[(df2[i] < ul) & (df2[i]>ll)]